// #2fbdea
// color palettes generated by https://material.io/inline-tools/color/
export const pictonBlue = {
  '50': '#def4fb',
  '100': '#ace3f5',
  '200': '#74d1ef',
  '300': '#2fbeea', // #2fbdea
  '400': '#00b1e9',
  '500': '#00a3e7',
  '600': '#0096d9',
  '700': '#0083c6',
  '800': '#0072b3',
  '900': '#005393',
};
