export enum AuthorSortEnum {
  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
  NAME = 'NAME',
  SURNAME = 'SURNAME',
  AGE = 'AGE',
  BIRTH_DATE = 'BIRTH_DATE',
  EMAIL = 'EMAIL',
  ADDRESS = 'ADDRESS',
  GENDER = 'GENDER',
}
