export const publicRuntimeConfig = {
  NEXT_PUBLIC_BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL,
  NEXT_PUBLIC_PLATFORM_URL: process.env.NEXT_PUBLIC_PLATFORM_URL,
  NEXT_PUBLIC_LOCALE_DEFAULT: process.env.NEXT_PUBLIC_LOCALE_DEFAULT,
};
