export enum BookSortEnum {
  CREATED_AT = 'CREATED_AT',
  UPDATED_AT = 'UPDATED_AT',
  TITLE = 'TITLE',
  PUBLISHING_DATE = 'PUBLISHING_DATE',
  PRICE = 'PRICE',
  DESCRIPTION = 'DESCRIPTION',
  PUBLISHED = 'PUBLISHED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
}
