name: ROQ One Backend CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.13"
          cache: "npm"
      - run: |
          npm ci
          npm run build
        working-directory: ./backend
